# Generated by Django 1.11.4 on 2017-08-16 06:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinycontent', '0003_update_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinycontentfileupload',
            name='file',
            field=models.FileField(upload_to='tinycontent/uploads'),
        ),
        migrations.AlterField(
            model_name='tinycontentfileupload',
            name='name',
            field=models.CharField(help_text='The name of the file.', max_length=60),
        ),
        migrations.AlterField(
            model_name='tinycontentfileupload',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
